# Default values for gok8r.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

api:
  service:
    type: NodePort
    port: 8000
    nodePort: 30000
  podName: "api"
  image: api
  tag: ""
  containerPort: 8000

frontend:
  service:
    type: NodePort
    port: 80
    nodePort: 30001
  podName: "frontend"
  image: frontend
  tag: ""
  containerPort: 80

broker:
  service:
    type: NodePort
    port: 15672
    nodePort: 30002

  podName: "broker"
  image: rabbitmq
  tag: ""
  containerPort: 15672 #5672

image:
    pullPolicy: Never
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "gok8r-service-user"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

readiness:
  initialDelaySeconds: 60
  periodSeconds: 5

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: gok8r.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
