apiVersion: v1
kind: Service
metadata:
  name: {{ include "gok8r-api.fullname" . }}-service
  labels:
    {{- include "gok8r-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "gok8r-api.selectorLabels" . | nindent 4 }}
