apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.podName }}-service
  labels:
    {{- include "gok8r.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      nodePort: {{ .Values.api.service.nodePort }}
      protocol: TCP
      name: api
  selector:
    {{- include "gok8r.selectorLabels" . | nindent 4 }}
